import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { pool, withTransaction } from '../db/pool.js';
import { env } from '../config/env.js';
import { badRequest, notFound } from '../core/errors.js';
import { resolveCustomerIdentity } from '../customer/identity.js';

const address=z.object({recipientName:z.string().trim().min(2).max(200),phone:z.string().trim().min(7).max(40),countryCode:z.string().length(2).default('AZ'),city:z.string().trim().min(2).max(120),district:z.string().trim().max(120).optional(),addressLine1:z.string().trim().min(5).max(300),addressLine2:z.string().trim().max(300).optional(),postalCode:z.string().trim().max(30).optional()});
const checkoutInput=z.object({customerEmail:z.email(),customerPhone:z.string().trim().min(7).max(40),customerName:z.string().trim().min(2).max(200),shippingAddress:address,billingAddress:address.optional(),customerNote:z.string().trim().max(1000).default(''),items:z.array(z.object({listingId:z.uuid(),variantId:z.uuid(),quantity:z.number().int().min(1).max(100)})).min(1).max(100)}).refine(v=>new Set(v.items.map(i=>i.variantId)).size===v.items.length,{path:['items'],message:'Eyni variant bir neçə dəfə göndərilə bilməz'});
interface CheckoutLine { listing_id:string; title:string; price:string; currency:string; product_id:string; vendor_id:string; sku:string; variant_id:string; variant_title:string; warehouse_id:string; commission_rate:string; quantity:number; unitCents:number; lineCents:number }

export async function checkoutRoutes(app:FastifyInstance):Promise<void>{
  app.post('/',{config:{rateLimit:{max:20,timeWindow:'15 minutes'}}},async(request,reply)=>{const input=checkoutInput.parse(request.body);const idempotency=z.string().min(16).max(200).parse(request.headers['idempotency-key']);const identity=await resolveCustomerIdentity(request,reply);const userId=identity.userId;const anonymousId=identity.anonymousId;
    const storeResult=await pool.query(`SELECT id,currency FROM stores WHERE code=$1 AND status='active'`,[env.DEFAULT_STORE_CODE]);const store=storeResult.rows[0];if(!store)throw notFound('Store');
    const data=await withTransaction(async(client)=>{const previous=await client.query('SELECT id,order_number,status,grand_total,currency FROM orders WHERE store_id=$1 AND idempotency_key=$2',[store.id,idempotency]);if(previous.rows[0])return previous.rows[0];
      const lines:CheckoutLine[]=[];for(const item of input.items){const result=await client.query<CheckoutLine>(`SELECT pl.id AS listing_id,pl.title,pl.price,pl.currency,p.id AS product_id,p.vendor_id,p.sku,pv.id AS variant_id,pv.title AS variant_title,i.warehouse_id,i.quantity,i.reserved,v.commission_rate FROM product_listings pl JOIN products p ON p.id=pl.product_id JOIN product_variants pv ON pv.product_id=p.id JOIN vendors v ON v.id=p.vendor_id JOIN warehouses w ON w.store_id=pl.store_id AND (w.vendor_id IS NULL OR w.vendor_id=p.vendor_id) JOIN inventory i ON i.variant_id=pv.id AND i.warehouse_id=w.id WHERE pl.id=$1 AND pv.id=$2 AND pl.store_id=$3 AND pl.status='published' AND p.status='published' AND v.status='active' AND i.quantity-i.reserved >= $4 ORDER BY (w.vendor_id IS NOT NULL) DESC,i.quantity-i.reserved DESC LIMIT 1 FOR UPDATE OF i`,[item.listingId,item.variantId,store.id,item.quantity]);const row=result.rows[0];if(!row)throw badRequest('ITEM_UNAVAILABLE','Məhsul mövcud deyil və ya stok kifayət etmir',{listingId:item.listingId,variantId:item.variantId});if(row.currency!==store.currency)throw badRequest('CURRENCY_MISMATCH','Məhsul valyutası store valyutası ilə uyğun deyil');const unitCents=Math.round(Number(row.price)*100);lines.push({...row,quantity:item.quantity,unitCents,lineCents:unitCents*item.quantity});}
      const subtotalCents=lines.reduce((sum,line)=>sum+line.lineCents,0);const order=await client.query(`INSERT INTO orders(store_id,user_id,anonymous_id,customer_email,customer_phone,customer_name,currency,subtotal,grand_total,shipping_address,billing_address,customer_note,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8,$9,$10,$11,$12) RETURNING *`,[store.id,userId,anonymousId,input.customerEmail.toLowerCase(),input.customerPhone,input.customerName,store.currency,subtotalCents/100,JSON.stringify(input.shippingAddress),JSON.stringify(input.billingAddress??input.shippingAddress),input.customerNote,idempotency]);const orderId=order.rows[0].id;
      const vendorGroups=new Map<string,CheckoutLine[]>();for(const line of lines){const group=vendorGroups.get(line.vendor_id)??[];group.push(line);vendorGroups.set(line.vendor_id,group);}for(const[vendorId,vendorLines]of vendorGroups){const first=vendorLines[0]!;const vendorSubtotal=vendorLines.reduce((sum,line)=>sum+line.lineCents,0);const commission=Math.round(vendorSubtotal*Number(first.commission_rate)/100);const vendorOrder=await client.query(`INSERT INTO vendor_orders(order_id,vendor_id,subtotal,commission_total,payout_total) VALUES($1,$2,$3,$4,$5) RETURNING id`,[orderId,vendorId,vendorSubtotal/100,commission/100,(vendorSubtotal-commission)/100]);for(const line of vendorLines){await client.query(`INSERT INTO order_items(order_id,vendor_order_id,vendor_id,product_id,variant_id,product_name,sku,quantity,unit_price,line_total,snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[orderId,vendorOrder.rows[0].id,vendorId,line.product_id,line.variant_id,line.title,line.sku,line.quantity,line.unitCents/100,line.lineCents/100,JSON.stringify({listingId:line.listing_id,variantTitle:line.variant_title})]);await client.query(`UPDATE inventory SET reserved=reserved+$3,updated_at=now() WHERE variant_id=$1 AND warehouse_id=$2`,[line.variant_id,line.warehouse_id,line.quantity]);await client.query(`INSERT INTO inventory_movements(variant_id,warehouse_id,movement_type,quantity_delta,reference_type,reference_id,note) VALUES($1,$2,'reservation',$3,'order',$4,'Checkout rezervi')`,[line.variant_id,line.warehouse_id,-line.quantity,orderId]);}await client.query(`INSERT INTO order_status_history(order_id,vendor_order_id,to_status,note) VALUES($1,$2,'pending','Sifariş yaradıldı')`,[orderId,vendorOrder.rows[0].id]);}
      await client.query(`INSERT INTO order_status_history(order_id,to_status,note) VALUES($1,'pending','Checkout tamamlandı')`,[orderId]);await client.query(`INSERT INTO outbox_events(topic,aggregate_type,aggregate_id,payload) VALUES('order.created','order',$1,$2)`,[orderId,JSON.stringify({orderId,orderNumber:order.rows[0].order_number,storeId:store.id,vendorIds:[...vendorGroups.keys()]})]);await client.query(`DELETE FROM carts WHERE store_id=$1 AND ${userId?'user_id=$2':'anonymous_id=$2'}`,[store.id,userId??anonymousId]);if(anonymousId){const names=input.customerName.trim().split(/\s+/);await client.query(`INSERT INTO customer_profiles(anonymous_id,first_name,last_name,display_name,email,phone) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(anonymous_id) WHERE anonymous_id IS NOT NULL DO UPDATE SET first_name=excluded.first_name,last_name=excluded.last_name,display_name=excluded.display_name,email=excluded.email,phone=excluded.phone`,[anonymousId,names[0]??'',names.slice(1).join(' '),input.customerName,input.customerEmail.toLowerCase(),input.customerPhone]);}return order.rows[0];});return reply.code(201).send({data:{id:data.id,orderNumber:data.order_number,status:data.status,paymentStatus:data.payment_status,grandTotal:data.grand_total,currency:data.currency}});});
}
