import { randomUUID } from 'node:crypto';
import { mkdir, unlink, writeFile } from 'node:fs/promises';
import { extname, resolve } from 'node:path';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { env } from '../config/env.js';
import { pool, withTransaction } from '../db/pool.js';
import { actorOf, assertStoreScope, assertVendorScope } from '../core/scope.js';
import { badRequest, notFound } from '../core/errors.js';
import { writeAudit } from '../core/audit.js';

const allowed=new Map([['image/jpeg','.jpg'],['image/png','.png'],['image/webp','.webp'],['image/avif','.avif'],['application/pdf','.pdf'],['video/mp4','.mp4'],['video/webm','.webm']]);
function validSignature(type:string,b:Buffer){if(type==='image/jpeg')return b[0]===0xff&&b[1]===0xd8;if(type==='image/png')return b.subarray(0,8).toString('hex')==='89504e470d0a1a0a';if(type==='image/webp')return b.subarray(0,4).toString()==='RIFF'&&b.subarray(8,12).toString()==='WEBP';if(type==='application/pdf')return b.subarray(0,5).toString()==='%PDF-';if(type==='video/mp4')return b.subarray(4,8).toString()==='ftyp';if(type==='video/webm')return b.subarray(0,4).toString('hex')==='1a45dfa3';if(type==='image/avif')return b.subarray(4,12).toString().includes('ftyp');return false;}
export async function mediaRoutes(app:FastifyInstance):Promise<void>{
  app.get('/',{preHandler:app.requirePermission('media.read')},async(request)=>{const actor=actorOf(request);const params:unknown[]=[];const where=['1=1'];if(actor.vendorIds.length){params.push(actor.vendorIds);where.push(`vendor_id=ANY($${params.length}::uuid[])`);}else if(!actor.isSuperAdmin){params.push(actor.storeIds);where.push(`store_id=ANY($${params.length}::uuid[])`);}const result=await pool.query(`SELECT * FROM media_assets WHERE ${where.join(' AND ')} ORDER BY created_at DESC LIMIT 100`,params);return{data:result.rows};});
  app.post('/',{preHandler:app.requirePermission('media.manage')},async(request,reply)=>{const part=await request.file();if(!part)throw badRequest('FILE_REQUIRED','Fayl tələb olunur');const fields=part.fields as Record<string,{value?:unknown}>;const input=z.object({storeId:z.uuid(),vendorId:z.uuid().optional(),altText:z.string().trim().max(300).default(''),title:z.string().trim().max(300).default('')}).parse({storeId:fields['storeId']?.value,vendorId:fields['vendorId']?.value||undefined,altText:fields['altText']?.value??'',title:fields['title']?.value??''});const actor=actorOf(request);assertStoreScope(actor,input.storeId);if(input.vendorId&&actor.vendorIds.length)assertVendorScope(actor,input.vendorId);if(actor.vendorIds.length&&!input.vendorId)throw badRequest('VENDOR_REQUIRED','Satıcı faylı vendor scope ilə yüklənməlidir');const extension=allowed.get(part.mimetype);if(!extension)throw badRequest('FILE_TYPE_REJECTED','Bu fayl tipi qəbul edilmir');const buffer=await part.toBuffer();if(!validSignature(part.mimetype,buffer))throw badRequest('FILE_SIGNATURE_INVALID','Fayl məzmunu tipi ilə uyğun deyil');if(part.mimetype.startsWith('image/')&&!input.altText)throw badRequest('ALT_REQUIRED','Şəkil üçün alt mətni SEO və əlçatanlıq baxımından tələb olunur');const key=`${input.storeId}/${new Date().toISOString().slice(0,7)}/${randomUUID()}${extension}`;const directory=resolve(env.UPLOAD_DIR,input.storeId,new Date().toISOString().slice(0,7));const target=resolve(env.UPLOAD_DIR,key);await mkdir(directory,{recursive:true});await writeFile(target,buffer,{flag:'wx'});try{const data=await withTransaction(async(client)=>{const result=await client.query(`INSERT INTO media_assets(store_id,vendor_id,uploaded_by,storage_key,public_url,mime_type,byte_size,alt_text,title,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[input.storeId,input.vendorId??null,actor.userId,key,`/uploads/${key}`,part.mimetype,buffer.length,input.altText,input.title,JSON.stringify({originalName:part.filename,sourceExtension:extname(part.filename)})]);await writeAudit(client,{actorUserId:actor.userId,storeId:input.storeId,vendorId:input.vendorId??null,action:'media.upload',entityType:'media_asset',entityId:result.rows[0].id,afterData:{storageKey:key,mimeType:part.mimetype,byteSize:buffer.length},requestId:request.id});return result.rows[0];});return reply.code(201).send({data});}catch(error){await unlink(target).catch(()=>undefined);throw error;}});
  app.patch('/:id',{preHandler:app.requirePermission('media.manage')},async(request)=>{const id=z.uuid().parse((request.params as{id:string}).id);const input=z.object({altText:z.string().trim().max(300),title:z.string().trim().max(300)}).partial().parse(request.body);const actor=actorOf(request);const current=await pool.query('SELECT * FROM media_assets WHERE id=$1',[id]);const row=current.rows[0];if(!row)throw notFound('Media');assertStoreScope(actor,row.store_id);if(actor.vendorIds.length&&row.vendor_id)assertVendorScope(actor,row.vendor_id);const result=await pool.query('UPDATE media_assets SET alt_text=coalesce($2,alt_text),title=coalesce($3,title) WHERE id=$1 RETURNING *',[id,input.altText??null,input.title??null]);return{data:result.rows[0]};});
}
