const state={user:null,view:'dashboard'};
const $=(s)=>document.querySelector(s);
const menus=[
  ['Əsas',[['dashboard','◫','İcmal','dashboard.read']]],
  ['Satış',[['orders','▤','Sifarişlər','orders.read'],['products','□','Məhsullar','catalog.read'],['inventory','▥','Anbar','inventory.read'],['vendors','◇','Satıcılar','vendors.read']]],
  ['Kontent',[['posts','≡','Məqalələr','cms.read'],['pages','▱','Səhifələr','cms.read'],['seo','⌕','SEO klasterləri','seo.read']]],
  ['Marketinq',[['campaigns','◎','Kampaniyalar','campaigns.read'],['coupons','◉','Kuponlar','coupons.read'],['qr','⌗','QR mərkəzi','qr.read']]],
  ['Sistem',[['users','♙','İstifadəçilər','users.read'],['settings','⚙','Parametrlər','settings.read']]]
];
const labels={dashboard:['İcmal','Platformanın ümumi vəziyyəti'],orders:['Sifarişlər','Satış əməliyyatları'],products:['Məhsullar','Kataloq və moderasiya'],inventory:['Anbar','Stok idarəetməsi'],vendors:['Satıcılar','Tərəfdaş hesabları'],posts:['Məqalələr','Redaksiya kontenti'],pages:['Səhifələr','Sayt səhifələri'],seo:['SEO klasterləri','Pillar–Cluster modeli'],campaigns:['Kampaniyalar','Marketinq fəaliyyətləri'],coupons:['Kuponlar','Endirim mexanizmləri'],qr:['QR mərkəzi','Dinamik QR və analitika'],users:['İstifadəçilər','Rol və giriş idarəetməsi'],settings:['Parametrlər','Platforma konfiqurasiyası']};
function cookie(name){return document.cookie.split('; ').find(x=>x.startsWith(`${name}=`))?.split('=').slice(1).join('=');}
async function api(path,options={},retry=true){const headers={'Content-Type':'application/json',...options.headers};const csrf=cookie('db_csrf')||cookie('__Host-db_csrf');if(csrf)headers['x-csrf-token']=decodeURIComponent(csrf);const res=await fetch(`/api/v1${path}`,{credentials:'include',...options,headers});if(res.status===401&&retry&&!path.includes('/auth/')){const refresh=await fetch('/api/v1/auth/refresh',{method:'POST',credentials:'include'});if(refresh.ok)return api(path,options,false);}if(res.status===204)return null;const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error?.message||'Sorğu yerinə yetirilmədi');return body;}
function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function money(v,c='AZN'){return new Intl.NumberFormat('az-AZ',{style:'currency',currency:c}).format(Number(v||0));}
function date(v){return v?new Intl.DateTimeFormat('az-AZ',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';}
function badge(v){return `<span class="badge ${esc(v)}">${esc(v)}</span>`;}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast show${error?' error':''}`;setTimeout(()=>el.className='toast',3000);}
function can(permission){return state.user?.permissions?.includes(permission);}
function renderNav(){const nav=$('#navigation');nav.innerHTML=menus.map(([section,items])=>{const links=items.filter(x=>can(x[3])).map(([id,icon,label])=>`<a href="#${id}" class="nav-link ${state.view===id?'active':''}" data-view="${id}"><i>${icon}</i>${label}</a>`).join('');return links?`<div class="nav-section">${section}</div>${links}`:'';}).join('');}
function table(columns,rows){return `<div class="panel"><div class="table-wrap"><table><thead><tr>${columns.map(c=>`<th>${c.label}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${columns.map(c=>`<td>${c.render?c.render(row):esc(row[c.key]??'—')}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${columns.length}" class="empty">Hələ məlumat yoxdur</td></tr>`}</tbody></table></div></div>`;}
async function dashboard(){const {data}=await api('/dashboard');return `<div class="stats-grid"><article class="stat-card"><span class="kicker">Bu ay sifariş</span><strong>${data.orders.total_orders}</strong><small>${data.orders.open_orders} aktiv sifariş</small></article><article class="stat-card"><span class="kicker">Ümumi satış</span><strong>${money(data.orders.gross_sales)}</strong><small>Cari ay üzrə</small></article><article class="stat-card"><span class="kicker">Dərc edilmiş məhsul</span><strong>${data.products.published}</strong><small>${data.products.pending} moderasiyada</small></article><article class="stat-card"><span class="kicker">QR skanları</span><strong>${data.qr.scans}</strong><small>${data.qr.codes} aktiv kod</small></article></div><div class="dashboard-grid"><section class="panel"><div class="panel-header"><h2>Sürətli əməliyyatlar</h2></div><div class="panel-body quick-grid">${[['products','Yeni məhsul','Kataloqa məhsul əlavə et'],['posts','Yeni məqalə','Redaksiya kontenti hazırla'],['campaigns','Kampaniya yarat','Endirim aksiyası başlat'],['qr','QR kod yarat','Ölçülə bilən QR hazırla']].map(x=>`<button class="quick-action" data-go="${x[0]}"><strong>${x[1]}</strong><small>${x[2]}</small></button>`).join('')}</div></section><section class="panel"><div class="panel-header"><h2>Platforma göstəriciləri</h2></div><div class="panel-body metric-list"><div class="metric-row"><span>Satıcı sayı</span><strong>${data.vendors.total}</strong></div><div class="metric-row"><span>Təsdiq gözləyən satıcı</span><strong>${data.vendors.pending}</strong></div><div class="metric-row"><span>QR kod sayı</span><strong>${data.qr.codes}</strong></div></div></section></div>`;}
const configs={
 orders:{path:'/orders',cols:[{label:'№',key:'order_number'},{label:'Müştəri',key:'customer_name'},{label:'Satıcı',key:'vendor_name'},{label:'Məbləğ',render:r=>money(r.vendor_subtotal,r.currency)},{label:'Status',render:r=>badge(r.vendor_status)},{label:'Tarix',render:r=>date(r.placed_at)}]},
 products:{path:'/catalog/products',cols:[{label:'SKU',key:'sku'},{label:'Məhsul',key:'title'},{label:'Satıcı',key:'vendor_name'},{label:'Qiymət',render:r=>money(r.price,r.currency)},{label:'Status',render:r=>badge(r.listing_status)},{label:'Tarix',render:r=>date(r.created_at)}]},
 vendors:{path:'/vendors',cols:[{label:'Satıcı',key:'display_name'},{label:'Hüquqi ad',key:'legal_name'},{label:'E-poçt',key:'email'},{label:'Komissiya',render:r=>`${r.commission_rate}%`},{label:'Status',render:r=>badge(r.status)},{label:'Tarix',render:r=>date(r.created_at)}]},
 users:{path:'/users',cols:[{label:'Ad',render:r=>`${esc(r.first_name)} ${esc(r.last_name)}`},{label:'E-poçt',key:'email'},{label:'Rollar',render:r=>(r.roles||[]).map(badge).join(' ')},{label:'Status',render:r=>badge(r.status)},{label:'Son giriş',render:r=>date(r.last_login_at)}]},
 posts:{path:'/content/posts',cols:[{label:'Başlıq',key:'title'},{label:'Slug',key:'slug'},{label:'Status',render:r=>badge(r.status)},{label:'SEO title',key:'seo_title'},{label:'Yenilənib',render:r=>date(r.updated_at)}]},
 pages:{path:'/content/pages',cols:[{label:'Başlıq',key:'title'},{label:'Slug',key:'slug'},{label:'Status',render:r=>badge(r.status)},{label:'SEO title',key:'seo_title'},{label:'Yenilənib',render:r=>date(r.updated_at)}]},
 campaigns:{path:'/marketing/campaigns',cols:[{label:'Kampaniya',key:'name'},{label:'Növ',key:'campaign_type'},{label:'Status',render:r=>badge(r.status)},{label:'Başlayır',render:r=>date(r.starts_at)},{label:'Bitir',render:r=>date(r.ends_at)}]},
 coupons:{path:'/marketing/coupons',cols:[{label:'Kupon',key:'name'},{label:'Növ',key:'discount_type'},{label:'Dəyər',key:'discount_value'},{label:'İstifadə',key:'redemption_count'},{label:'Status',render:r=>badge(r.status)},{label:'Bitir',render:r=>date(r.expires_at)}]},
 qr:{path:'/marketing/qr',cols:[{label:'QR',key:'name'},{label:'Kod',key:'code'},{label:'Növ',key:'qr_type'},{label:'Skan',key:'scan_count'},{label:'Status',render:r=>badge(r.status)},{label:'Bitir',render:r=>date(r.expires_at)}]},
 seo:{path:'/content/seo/clusters',cols:[{label:'Klaster',key:'name'},{label:'Əsas açar söz',key:'primary_keyword'},{label:'Axtarış niyyəti',key:'search_intent'},{label:'Pillar',render:r=>esc(r.pillar_page_title||r.pillar_post_title||'—')},{label:'Cluster sayı',key:'member_count'},{label:'Status',render:r=>badge(r.status)}]}
};
async function listing(view){const config=configs[view];const result=await api(config.path);return `<div class="page-actions"><button class="primary" data-create="${view}">+ Yeni əlavə et</button></div>${table(config.cols,result.data||[])}`;}
async function placeholder(){return `<section class="panel"><div class="empty"><h2>Modul hazırlanıb</h2><p>Bu bölmənin API və icazə infrastrukturu aktivdir. Məlumat olduqda burada göstəriləcək.</p></div></section>`;}
const field=(name,label,type='text',required=true,options=[])=>`<label>${label}${type==='select'?`<select name="${name}" ${required?'required':''}>${options.map(([value,text])=>`<option value="${esc(value)}">${esc(text)}</option>`).join('')}</select>`:type==='textarea'?`<textarea name="${name}" ${required?'required':''}></textarea>`:`<input name="${name}" type="${type}" ${required?'required':''}>`}</label>`;
async function vendors(){if(state.user.vendorIds.length)return state.user.vendorIds.map(id=>[id,'Mənim satıcı hesabım']);const result=await api('/vendors?limit=100');return result.data.map(v=>[v.id,v.display_name]);}
async function openCreate(view){const storeId=state.user.storeIds[0];if(!storeId)throw new Error('Store scope tapılmadı');const vendorList=['products','users','campaigns','coupons','qr'].includes(view)?await vendors():[];let fields='';
 if(view==='vendors')fields=field('displayName','Görünən ad')+field('legalName','Hüquqi ad')+field('email','E-poçt','email')+field('phone','Telefon','tel',false)+field('commissionRate','Komissiya faizi','number')+field('description','Təsvir','textarea',false);
 else if(view==='products')fields=field('vendorId','Satıcı','select',true,vendorList)+field('sku','SKU')+field('name','Məhsul adı')+field('price','Qiymət','number')+field('shortDescription','Qısa təsvir','textarea')+field('description','Ətraflı təsvir','textarea')+field('seoTitle','SEO title')+field('seoDescription','Meta description');
 else if(view==='users')fields=field('firstName','Ad')+field('lastName','Soyad')+field('email','E-poçt','email')+field('temporaryPassword','Müvəqqəti şifrə','password')+field('roleCode','Rol','select',true,[['admin','Admin'],['editor','Redaktor'],['seo','SEO'],['moderator','Moderator'],['vendor_owner','Satıcı sahibi'],['vendor_staff','Satıcı işçisi']])+field('vendorId','Satıcı','select',false,[['','Seçilməyib'],...vendorList]);
 else if(view==='pages'||view==='posts')fields=field('title','Başlıq')+field('slug','Slug','text',false)+field('excerpt','Xülasə','textarea')+field('body','Əsas mətn','textarea')+field('seoTitle','SEO title')+field('seoDescription','Meta description');
 else if(view==='seo')fields=field('name','Klaster adı')+field('primaryKeyword','Əsas açar söz')+field('searchIntent','Axtarış niyyəti','select',true,[['informational','Məlumat'],['commercial','Kommersiya'],['transactional','Tranzaksiya'],['local','Lokal']])+field('targetAudience','Hədəf auditoriya','textarea',false);
 else if(view==='campaigns')fields=field('name','Kampaniya adı')+field('slug','Slug')+field('campaignType','Növ','select',true,[['daily_deal','Günün təklifi'],['weekly','Həftəlik'],['limited','Məhdud'],['seasonal','Mövsümi'],['other','Digər']])+field('vendorId','Satıcı','select',state.user.vendorIds.length>0,[['','Platforma'],...vendorList])+field('startsAt','Başlama','datetime-local')+field('endsAt','Bitmə','datetime-local')+field('description','Təsvir','textarea',false);
 else if(view==='coupons')fields=field('name','Kupon adı')+field('codePrefix','Kod prefiksi')+field('discountType','Növ','select',true,[['percentage','Faiz'],['fixed_amount','Sabit məbləğ'],['free_shipping','Pulsuz çatdırılma']])+field('discountValue','Dəyər','number')+field('vendorId','Satıcı','select',state.user.vendorIds.length>0,[['','Platforma'],...vendorList])+field('startsAt','Başlama','datetime-local')+field('expiresAt','Bitmə','datetime-local');
 else if(view==='qr')fields=field('name','QR adı')+field('qrType','Növ','select',true,[['smart','Smart'],['social','Sosial'],['lead','Lead'],['store','Store']])+field('vendorId','Satıcı','select',state.user.vendorIds.length>0,[['','Platforma'],...vendorList])+field('targetUrl','Hədəf URL','url');else return toast('Bu bölmədə yaradılma əməliyyatı ayrıca workflow ilə aparılır');
 $('#dialogTitle').textContent=`${labels[view][0]} — yeni qeyd`;$('#formFields').innerHTML=fields;$('#createForm').dataset.view=view;$('#createForm').dataset.storeId=storeId;$('#createError').textContent='';$('#createDialog').showModal();}
$('#createForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const view=form.dataset.view;let body=Object.fromEntries([...new FormData(form)].filter(([,value])=>value!==''));body.storeId=form.dataset.storeId;let path='';try{if(view==='vendors'){path='/vendors';body.commissionRate=Number(body.commissionRate||0);}else if(view==='products'){path='/catalog/products';body={...body,price:Number(body.price),currency:'AZN',categoryIds:[],attributes:{},variant:{sku:body.sku,title:'Standart'}};}else if(view==='users'){path='/users';}else if(view==='pages'||view==='posts'){path=`/content/${view}`;body.content=[{type:'paragraph',data:{html:body.body}}];delete body.body;}else if(view==='seo'){path='/content/seo/clusters';}else if(view==='campaigns'){path='/marketing/campaigns';body={...body,startsAt:new Date(body.startsAt).toISOString(),endsAt:new Date(body.endsAt).toISOString(),goals:{},targeting:{}};}else if(view==='coupons'){path='/marketing/coupons';body={...body,discountValue:Number(body.discountValue),minimumOrder:0,perUserLimit:1,startsAt:new Date(body.startsAt).toISOString(),expiresAt:new Date(body.expiresAt).toISOString(),rules:{}};}else if(view==='qr'){path='/marketing/qr';body={...body,perUserLimit:1,rules:{}};}await api(path,{method:'POST',body:JSON.stringify(body)});$('#createDialog').close();toast('Qeyd uğurla yaradıldı');render();}catch(error){$('#createError').textContent=error.message;}});
$('#closeDialog').addEventListener('click',()=>$('#createDialog').close());$('#cancelDialog').addEventListener('click',()=>$('#createDialog').close());
async function render(){state.view=location.hash.slice(1)||'dashboard';if(!labels[state.view])state.view='dashboard';renderNav();const [title,eyebrow]=labels[state.view];$('#pageTitle').textContent=title;$('#pageEyebrow').textContent=eyebrow.toUpperCase();$('#content').innerHTML='<div class="loader">Məlumatlar yüklənir…</div>';try{$('#content').innerHTML=state.view==='dashboard'?await dashboard():configs[state.view]?await listing(state.view):await placeholder();}catch(error){$('#content').innerHTML=`<div class="panel empty"><h2>Məlumat yüklənmədi</h2><p>${esc(error.message)}</p></div>`;}}
async function boot(){try{const {data}=await api('/auth/me',{},false);state.user=data;$('#loginView').hidden=true;$('#appView').hidden=false;$('#userName').textContent=`${data.firstName} ${data.lastName}`;$('#userRole').textContent=data.roles.join(', ');$('#avatar').textContent=`${data.firstName[0]}${data.lastName[0]}`.toUpperCase();render();}catch{$('#appView').hidden=true;$('#loginView').hidden=false;}}
$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();$('#loginError').textContent='';const form=new FormData(event.currentTarget);try{await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(form))},false);await boot();}catch(error){$('#loginError').textContent=error.message;}});
$('#logoutButton').addEventListener('click',async()=>{try{await api('/auth/logout',{method:'POST'});}finally{state.user=null;location.hash='';boot();}});
$('#menuButton').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
document.addEventListener('click',event=>{const go=event.target.closest('[data-go]');if(go)location.hash=go.dataset.go;const create=event.target.closest('[data-create]');if(create)openCreate(create.dataset.create).catch(error=>toast(error.message,true));if(event.target.closest('.nav-link'))$('#sidebar').classList.remove('open');});
addEventListener('hashchange',render);boot();
